# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LULCgui.ui'
#
# Created: Wed Jun  5 16:00:01 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_LULCModel(object):
    def setupUi(self, LULCModel):
        LULCModel.setObjectName(_fromUtf8("LULCModel"))
        LULCModel.resize(794, 639)
        self.centralwidget = QtGui.QWidget(LULCModel)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.DataPreparation = QtGui.QWidget()
        self.DataPreparation.setObjectName(_fromUtf8("DataPreparation"))
        self.gridLayoutWidget = QtGui.QWidget(self.DataPreparation)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 29459, 551))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_6 = QtGui.QGroupBox(self.gridLayoutWidget)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.groupBox_6)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 20, 781, 241))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_10 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_10.addWidget(self.label_9, 0, 0, 1, 1)
        self.leOutputFile = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.leOutputFile.setText(_fromUtf8(""))
        self.leOutputFile.setObjectName(_fromUtf8("leOutputFile"))
        self.gridLayout_10.addWidget(self.leOutputFile, 0, 1, 1, 1)
        self.pbSelectFile_OutputFile = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.pbSelectFile_OutputFile.setObjectName(_fromUtf8("pbSelectFile_OutputFile"))
        self.gridLayout_10.addWidget(self.pbSelectFile_OutputFile, 0, 2, 1, 1)
        self.pbNextDataPreparation = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.pbNextDataPreparation.setObjectName(_fromUtf8("pbNextDataPreparation"))
        self.gridLayout_10.addWidget(self.pbNextDataPreparation, 2, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem, 1, 2, 1, 1)
        self.tbLog = QtGui.QTextBrowser(self.gridLayoutWidget_5)
        self.tbLog.setEnabled(False)
        self.tbLog.setFrameShape(QtGui.QFrame.Box)
        self.tbLog.setOverwriteMode(True)
        self.tbLog.setObjectName(_fromUtf8("tbLog"))
        self.gridLayout_10.addWidget(self.tbLog, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_6, 3, 2, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.gridLayoutWidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 30, 781, 241))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 2, 3, 1, 1)
        self.cbCreateGrid_TO = QtGui.QCheckBox(self.layoutWidget)
        self.cbCreateGrid_TO.setObjectName(_fromUtf8("cbCreateGrid_TO"))
        self.gridLayout_2.addWidget(self.cbCreateGrid_TO, 2, 5, 1, 1)
        self.pbConvert_T0 = QtGui.QPushButton(self.layoutWidget)
        self.pbConvert_T0.setEnabled(False)
        self.pbConvert_T0.setObjectName(_fromUtf8("pbConvert_T0"))
        self.gridLayout_2.addWidget(self.pbConvert_T0, 2, 6, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 3, 3, 1, 1)
        self.pbConvert_T1 = QtGui.QPushButton(self.layoutWidget)
        self.pbConvert_T1.setEnabled(False)
        self.pbConvert_T1.setObjectName(_fromUtf8("pbConvert_T1"))
        self.gridLayout_2.addWidget(self.pbConvert_T1, 3, 6, 1, 1)
        self.cbCreateGrid_T1 = QtGui.QCheckBox(self.layoutWidget)
        self.cbCreateGrid_T1.setObjectName(_fromUtf8("cbCreateGrid_T1"))
        self.gridLayout_2.addWidget(self.cbCreateGrid_T1, 3, 5, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.pbSelectFile_T0 = QtGui.QPushButton(self.layoutWidget)
        self.pbSelectFile_T0.setObjectName(_fromUtf8("pbSelectFile_T0"))
        self.gridLayout_2.addWidget(self.pbSelectFile_T0, 2, 2, 1, 1)
        self.pbSelectFile_T1 = QtGui.QPushButton(self.layoutWidget)
        self.pbSelectFile_T1.setObjectName(_fromUtf8("pbSelectFile_T1"))
        self.gridLayout_2.addWidget(self.pbSelectFile_T1, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.pbSelectDirectory = QtGui.QPushButton(self.layoutWidget)
        self.pbSelectDirectory.setObjectName(_fromUtf8("pbSelectDirectory"))
        self.gridLayout_2.addWidget(self.pbSelectDirectory, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.pbSelectFile_Mask = QtGui.QPushButton(self.layoutWidget)
        self.pbSelectFile_Mask.setObjectName(_fromUtf8("pbSelectFile_Mask"))
        self.gridLayout_2.addWidget(self.pbSelectFile_Mask, 4, 2, 1, 1)
        self.leT0File = QtGui.QLineEdit(self.layoutWidget)
        self.leT0File.setText(_fromUtf8(""))
        self.leT0File.setObjectName(_fromUtf8("leT0File"))
        self.gridLayout_2.addWidget(self.leT0File, 2, 1, 1, 1)
        self.leT1File = QtGui.QLineEdit(self.layoutWidget)
        self.leT1File.setText(_fromUtf8(""))
        self.leT1File.setObjectName(_fromUtf8("leT1File"))
        self.gridLayout_2.addWidget(self.leT1File, 3, 1, 1, 1)
        self.leMaskFile = QtGui.QLineEdit(self.layoutWidget)
        self.leMaskFile.setText(_fromUtf8(""))
        self.leMaskFile.setObjectName(_fromUtf8("leMaskFile"))
        self.gridLayout_2.addWidget(self.leMaskFile, 4, 1, 1, 1)
        self.leYear_TO = QtGui.QLineEdit(self.layoutWidget)
        self.leYear_TO.setText(_fromUtf8(""))
        self.leYear_TO.setMaxLength(4)
        self.leYear_TO.setObjectName(_fromUtf8("leYear_TO"))
        self.gridLayout_2.addWidget(self.leYear_TO, 2, 4, 1, 1)
        self.leYear_T1 = QtGui.QLineEdit(self.layoutWidget)
        self.leYear_T1.setText(_fromUtf8(""))
        self.leYear_T1.setMaxLength(4)
        self.leYear_T1.setObjectName(_fromUtf8("leYear_T1"))
        self.gridLayout_2.addWidget(self.leYear_T1, 3, 4, 1, 1)
        self.cbCreateGrid_Mask = QtGui.QCheckBox(self.layoutWidget)
        self.cbCreateGrid_Mask.setObjectName(_fromUtf8("cbCreateGrid_Mask"))
        self.gridLayout_2.addWidget(self.cbCreateGrid_Mask, 4, 5, 1, 1)
        self.pbConvert_Mask = QtGui.QPushButton(self.layoutWidget)
        self.pbConvert_Mask.setEnabled(False)
        self.pbConvert_Mask.setObjectName(_fromUtf8("pbConvert_Mask"))
        self.gridLayout_2.addWidget(self.pbConvert_Mask, 4, 6, 1, 1)
        self.leProjectDirectory = QtGui.QLineEdit(self.layoutWidget)
        self.leProjectDirectory.setText(_fromUtf8(""))
        self.leProjectDirectory.setObjectName(_fromUtf8("leProjectDirectory"))
        self.gridLayout_2.addWidget(self.leProjectDirectory, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.sbGridsize = QtGui.QSpinBox(self.layoutWidget)
        self.sbGridsize.setEnabled(True)
        self.sbGridsize.setMinimum(65)
        self.sbGridsize.setMaximum(250000)
        self.sbGridsize.setSingleStep(50)
        self.sbGridsize.setProperty("value", 1000)
        self.sbGridsize.setObjectName(_fromUtf8("sbGridsize"))
        self.gridLayout_2.addWidget(self.sbGridsize, 1, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 1, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 2, 2, 1, 1)
        self.tabWidget.addTab(self.DataPreparation, _fromUtf8(""))
        self.DriverSelectionT0 = QtGui.QWidget()
        self.DriverSelectionT0.setEnabled(True)
        self.DriverSelectionT0.setObjectName(_fromUtf8("DriverSelectionT0"))
        self.groupBox = QtGui.QGroupBox(self.DriverSelectionT0)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 771, 261))
        self.groupBox.setMinimumSize(QtCore.QSize(4, 3))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.pbAddDriver = QtGui.QPushButton(self.groupBox)
        self.pbAddDriver.setEnabled(True)
        self.pbAddDriver.setObjectName(_fromUtf8("pbAddDriver"))
        self.gridLayout_7.addWidget(self.pbAddDriver, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_6 = QtGui.QPushButton(self.groupBox)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_3.addWidget(self.pushButton_6, 1, 1, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.groupBox)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.DriverSelectionT0)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 260, 771, 281))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_2 = QtGui.QGroupBox(self.verticalLayoutWidget_4)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 741, 251))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.pushButton_17 = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.gridLayout_9.addWidget(self.pushButton_17, 1, 1, 1, 1)
        self.pushButton_19 = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.gridLayout_9.addWidget(self.pushButton_19, 4, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 4, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.gridLayoutWidget_4)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit_2.setEnabled(True)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(3, 20, 641, 161))
        self.plainTextEdit_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plainTextEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit_2.setLineWrapMode(QtGui.QPlainTextEdit.WidgetWidth)
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.gridLayout_9.addWidget(self.groupBox_3, 2, 0, 2, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.rbMLP = QtGui.QRadioButton(self.gridLayoutWidget_4)
        self.rbMLP.setObjectName(_fromUtf8("rbMLP"))
        self.gridLayout_8.addWidget(self.rbMLP, 1, 3, 1, 1)
        self.rbIS = QtGui.QRadioButton(self.gridLayoutWidget_4)
        self.rbIS.setChecked(True)
        self.rbIS.setObjectName(_fromUtf8("rbIS"))
        self.gridLayout_8.addWidget(self.rbIS, 1, 0, 1, 1)
        self.rbLogR = QtGui.QRadioButton(self.gridLayoutWidget_4)
        self.rbLogR.setChecked(False)
        self.rbLogR.setObjectName(_fromUtf8("rbLogR"))
        self.gridLayout_8.addWidget(self.rbLogR, 1, 1, 1, 1)
        self.rbLinR = QtGui.QRadioButton(self.gridLayoutWidget_4)
        self.rbLinR.setObjectName(_fromUtf8("rbLinR"))
        self.gridLayout_8.addWidget(self.rbLinR, 1, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.DriverSelectionT0, _fromUtf8(""))
        self.DriverSelectionT1 = QtGui.QWidget()
        self.DriverSelectionT1.setObjectName(_fromUtf8("DriverSelectionT1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.DriverSelectionT1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_7 = QtGui.QGroupBox(self.DriverSelectionT1)
        self.groupBox_7.setMinimumSize(QtCore.QSize(4, 3))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tableWidget_2 = QtGui.QTableWidget(self.groupBox_7)
        self.tableWidget_2.setEnabled(True)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(9)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_2.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_2.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_2.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(2, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_2.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(3, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_2.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(4, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(4, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_2.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(5, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(5, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(5, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_2.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(6, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(6, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_2.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(7, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(7, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_2.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(8, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(8, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(8, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(8, 5, item)
        self.horizontalLayout_3.addWidget(self.tableWidget_2)
        self.horizontalLayout_4.addWidget(self.groupBox_7)
        self.tabWidget.addTab(self.DriverSelectionT1, _fromUtf8(""))
        self.CreateSutiabilityMap = QtGui.QWidget()
        self.CreateSutiabilityMap.setObjectName(_fromUtf8("CreateSutiabilityMap"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.CreateSutiabilityMap)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 891, 251))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_10 = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_10.setMinimumSize(QtCore.QSize(4, 3))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tableWidget_5 = QtGui.QTableWidget(self.groupBox_10)
        self.tableWidget_5.setObjectName(_fromUtf8("tableWidget_5"))
        self.tableWidget_5.setColumnCount(5)
        self.tableWidget_5.setRowCount(9)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(4, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(5, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(5, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(6, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(7, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(8, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(8, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(8, 4, item)
        self.horizontalLayout_6.addWidget(self.tableWidget_5)
        self.gridLayout_4.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.CreateSutiabilityMap)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 250, 841, 231))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.tableWidget_6 = QtGui.QTableWidget(self.groupBox_5)
        self.tableWidget_6.setGeometry(QtCore.QRect(0, 20, 871, 231))
        self.tableWidget_6.setObjectName(_fromUtf8("tableWidget_6"))
        self.tableWidget_6.setColumnCount(10)
        self.tableWidget_6.setRowCount(9)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_6.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(2, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(2, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(3, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(3, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(4, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(4, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(4, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(5, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(5, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(5, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(5, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(6, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(6, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(6, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(7, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(7, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(7, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(8, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(8, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(8, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_6.setItem(8, 6, item)
        self.tabWidget.addTab(self.CreateSutiabilityMap, _fromUtf8(""))
        self.DemandAllocation = QtGui.QWidget()
        self.DemandAllocation.setObjectName(_fromUtf8("DemandAllocation"))
        self.groupBox_9 = QtGui.QGroupBox(self.DemandAllocation)
        self.groupBox_9.setGeometry(QtCore.QRect(0, 0, 891, 211))
        self.groupBox_9.setMinimumSize(QtCore.QSize(4, 3))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tableWidget_4 = QtGui.QTableWidget(self.groupBox_9)
        self.tableWidget_4.setObjectName(_fromUtf8("tableWidget_4"))
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_4.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_4.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_4.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_4.setItem(5, 3, item)
        self.horizontalLayout_5.addWidget(self.tableWidget_4)
        self.pushButton_8 = QtGui.QPushButton(self.DemandAllocation)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 230, 902, 27))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.tabWidget.addTab(self.DemandAllocation, _fromUtf8(""))
        self.ComposeRaster = QtGui.QWidget()
        self.ComposeRaster.setObjectName(_fromUtf8("ComposeRaster"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.ComposeRaster)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_11 = QtGui.QLabel(self.ComposeRaster)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_11.addWidget(self.label_11, 0, 0, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.ComposeRaster)
        self.spinBox_2.setProperty("value", 2)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_11.addWidget(self.spinBox_2, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 0, 2, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.ComposeRaster)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_11.addWidget(self.lineEdit_2, 0, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.ComposeRaster)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_11.addWidget(self.label_8, 0, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 0, 5, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.tableWidget1 = QtGui.QTableWidget(self.ComposeRaster)
        self.tableWidget1.setObjectName(_fromUtf8("tableWidget1"))
        self.tableWidget1.setColumnCount(3)
        self.tableWidget1.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setItem(1, 2, item)
        self.gridLayout_6.addWidget(self.tableWidget1, 1, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.ComposeRaster)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_6.addWidget(self.pushButton, 2, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_6)
        self.tabWidget.addTab(self.ComposeRaster, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setMaximum(60)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_2.addWidget(self.progressBar)
        LULCModel.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(LULCModel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        LULCModel.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(LULCModel)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        LULCModel.setStatusBar(self.statusbar)

        self.retranslateUi(LULCModel)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.cbCreateGrid_TO, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbConvert_T0.setEnabled)
        QtCore.QObject.connect(self.cbCreateGrid_T1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbConvert_T1.setEnabled)
        QtCore.QObject.connect(self.cbCreateGrid_Mask, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbConvert_Mask.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(LULCModel)

    def retranslateUi(self, LULCModel):
        LULCModel.setWindowTitle(QtGui.QApplication.translate("LULCModel", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("LULCModel", "Output Section", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("LULCModel", "  Output File: ", None, QtGui.QApplication.UnicodeUTF8))
        self.leOutputFile.setPlaceholderText(QtGui.QApplication.translate("LULCModel", "Output Raster File", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSelectFile_OutputFile.setText(QtGui.QApplication.translate("LULCModel", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNextDataPreparation.setText(QtGui.QApplication.translate("LULCModel", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("LULCModel", "Input Section", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("LULCModel", "Year:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbCreateGrid_TO.setText(QtGui.QApplication.translate("LULCModel", "Create Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.pbConvert_T0.setText(QtGui.QApplication.translate("LULCModel", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("LULCModel", "Year:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbConvert_T1.setText(QtGui.QApplication.translate("LULCModel", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.cbCreateGrid_T1.setText(QtGui.QApplication.translate("LULCModel", "Create Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("LULCModel", "T0 File: ", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSelectFile_T0.setText(QtGui.QApplication.translate("LULCModel", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSelectFile_T1.setText(QtGui.QApplication.translate("LULCModel", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("LULCModel", " Project Directory: ", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSelectDirectory.setText(QtGui.QApplication.translate("LULCModel", "Select Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("LULCModel", "T1 File: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("LULCModel", "Mask File: ", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSelectFile_Mask.setText(QtGui.QApplication.translate("LULCModel", "Mask File", None, QtGui.QApplication.UnicodeUTF8))
        self.leT0File.setPlaceholderText(QtGui.QApplication.translate("LULCModel", "/file/path.shp", None, QtGui.QApplication.UnicodeUTF8))
        self.leT1File.setPlaceholderText(QtGui.QApplication.translate("LULCModel", "/file/path.shp", None, QtGui.QApplication.UnicodeUTF8))
        self.leMaskFile.setPlaceholderText(QtGui.QApplication.translate("LULCModel", "/file/mask.tiff", None, QtGui.QApplication.UnicodeUTF8))
        self.leYear_TO.setPlaceholderText(QtGui.QApplication.translate("LULCModel", "1985", None, QtGui.QApplication.UnicodeUTF8))
        self.leYear_T1.setPlaceholderText(QtGui.QApplication.translate("LULCModel", "1995", None, QtGui.QApplication.UnicodeUTF8))
        self.cbCreateGrid_Mask.setText(QtGui.QApplication.translate("LULCModel", "Create Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.pbConvert_Mask.setText(QtGui.QApplication.translate("LULCModel", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.leProjectDirectory.setPlaceholderText(QtGui.QApplication.translate("LULCModel", "Project Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("LULCModel", "Gridsize: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("LULCModel", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("LULCModel", "NA Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DataPreparation), QtGui.QApplication.translate("LULCModel", "Data Preparation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("LULCModel", "Select Drivers", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddDriver.setText(QtGui.QApplication.translate("LULCModel", "Add Driver ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("LULCModel", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("LULCModel", "Driver Name", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("LULCModel", "File Location", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("LULCModel", "File", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("LULCModel", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("LULCModel", "Do Model Fitting", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_17.setText(QtGui.QApplication.translate("LULCModel", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_19.setText(QtGui.QApplication.translate("LULCModel", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("LULCModel", "Model ParaMeter Output", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit_2.setPlainText(QtGui.QApplication.translate("LULCModel", "$BU\n"
"\n"
"Call:  glm(formula = frml, family = binomial, data = dta, na.action = \"na.omit\")\n"
"\n"
"Coefficients:\n"
" (Intercept)         slope     elevation      distourban  disttostream  \n"
"    -0.57087      -4.89053       0.05153     -17.37234      -1.70906  \n"
"\n"
"Degrees of Freedom: 59595 Total (i.e. Null);  59591 Residual\n"
"Null Deviance:        10680 \n"
"Residual Deviance: 7545     AIC: 7555 \n"
"\n"
"$DBF\n"
"\n"
"Call:  glm(formula = frml, family = binomial, data = dta, na.action = \"na.omit\")\n"
"\n"
"Coefficients:\n"
" (Intercept)         slope     elevation      distoueb  disttostream  \n"
"       7.987       -34.403       -21.125        -2.261         6.107  \n"
"\n"
"Degrees of Freedom: 59595 Total (i.e. Null);  59591 Residual\n"
"Null Deviance:        80660 \n"
"Residual Deviance: 46930     AIC: 46940 \n"
"\n"
"$class_2\n"
"\n"
"Call:  glm(formula = frml, family = binomial, data = dta, na.action = \"na.omit\")\n"
"\n"
"Coefficients:\n"
" (Intercept)         slope     elevation      distoueb  disttostream  \n"
"   -12.20462      21.68842      27.38513       0.38717      -0.06995  \n"
"\n"
"Degrees of Freedom: 59595 Total (i.e. Null);  59591 Residual\n"
"Null Deviance:        57860 \n"
"Residual Deviance: 21460     AIC: 21470 \n"
"\n"
"$class_3\n"
"\n"
"Call:  glm(formula = frml, family = binomial, data = dta, na.action = \"na.omit\")\n"
"\n"
"Coefficients:\n"
" (Intercept)         slope     elevation      distoueb  disttostream  \n"
"     -4.3284      -14.1903        5.2027       -0.7028       -3.8388  \n"
"\n"
"Degrees of Freedom: 59595 Total (i.e. Null);  59591 Residual\n"
"Null Deviance:        13500 \n"
"Residual Deviance: 12930     AIC: 12940 \n"
"\n"
"$class_4\n"
"\n"
"Call:  glm(formula = frml, family = binomial, data = dta, na.action = \"na.omit\")\n"
"\n"
"Coefficients:\n"
" (Intercept)         slope     elevation      distoueb  disttostream  \n"
"      -49.82        -61.62        -38.16         59.76         26.86  \n"
"\n"
"Degrees of Freedom: 59595 Total (i.e. Null);  59591 Residual\n"
"Null Deviance:        103.9 \n"
"Residual Deviance: 50.08     AIC: 60.08 \n"
"\n"
"$class_5\n"
"\n"
"Call:  glm(formula = frml, family = binomial, data = dta, na.action = \"na.omit\")\n"
"\n"
"Coefficients:\n"
" (Intercept)         slope     elevation      distoueb  disttostream  \n"
"      -8.341       -21.818        12.360        -6.098        -5.947  \n"
"\n"
"Degrees of Freedom: 59595 Total (i.e. Null);  59591 Residual\n"
"Null Deviance:        892.6 \n"
"Residual Deviance: 792.2     AIC: 802.2 \n"
"\n"
"$class_6\n"
"\n"
"Call:  glm(formula = frml, family = binomial, data = dta, na.action = \"na.omit\")\n"
"\n"
"Coefficients:\n"
" (Intercept)         slope     elevation      distoueb  disttostream  \n"
"     -3.8802       -6.2561        0.8099        2.2640        0.9813  \n"
"\n"
"Degrees of Freedom: 59595 Total (i.e. Null);  59591 Residual\n"
"Null Deviance:        28320 \n"
"Residual Deviance: 27090     AIC: 27100 \n"
"\n"
"$class_7\n"
"\n"
"Call:  glm(formula = frml, family = binomial, data = dta, na.action = \"na.omit\")\n"
"\n"
"Coefficients:\n"
" (Intercept)         slope     elevation      distoueb  disttostream  \n"
"      0.2006        5.8160      -13.2106        2.0149       -7.7734  \n"
"\n"
"Degrees of Freedom: 59595 Total (i.e. Null);  59591 Residual\n"
"Null Deviance:        13850 \n"
"Residual Deviance: 11840     AIC: 11850 \n"
"\n"
"$class_8\n"
"\n"
"Call:  glm(formula = frml, family = binomial, data = dta, na.action = \"na.omit\")\n"
"\n"
"Coefficients:\n"
" (Intercept)         slope     elevation      distoueb  disttostream  \n"
"      1.9138       -4.2583       -0.7237        0.6141     -206.6887  \n"
"\n"
"Degrees of Freedom: 59595 Total (i.e. Null);  59591 Residual\n"
"Null Deviance:        35680 \n"
"Residual Deviance: 8416     AIC: 8426 \n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.rbMLP.setText(QtGui.QApplication.translate("LULCModel", "MLP", None, QtGui.QApplication.UnicodeUTF8))
        self.rbIS.setText(QtGui.QApplication.translate("LULCModel", "Individualy Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.rbLogR.setText(QtGui.QApplication.translate("LULCModel", "Logistic Regression", None, QtGui.QApplication.UnicodeUTF8))
        self.rbLinR.setText(QtGui.QApplication.translate("LULCModel", "Linear Regression", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DriverSelectionT0), QtGui.QApplication.translate("LULCModel", "Driver Selection T0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("LULCModel", "Select Drivers", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("LULCModel", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("LULCModel", "2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("LULCModel", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("LULCModel", "4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("LULCModel", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("LULCModel", "6", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("LULCModel", "7", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("LULCModel", "8", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("LULCModel", "9", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("LULCModel", "Class", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("LULCModel", "ClassNumber", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("LULCModel", "slope", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("LULCModel", "elevation", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("LULCModel", "distourban", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("LULCModel", "distostream", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "BU", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(0, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "0", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(0, 2)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/slope.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(0, 3)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/elevation.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(0, 4)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(0, 5)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(1, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "DBF", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(1, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(1, 2)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/slope.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(1, 3)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/elevation.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(1, 4)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(1, 5)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(2, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "CL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(2, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(2, 2)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/slope.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(2, 3)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/elevation.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(2, 4)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(2, 5)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(3, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "FL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(3, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(3, 2)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/slope.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(3, 3)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/elevation.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(3, 4)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(3, 5)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(4, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "GL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(4, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(4, 2)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/slope.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(4, 3)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/elevation.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(4, 4)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(4, 5)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(5, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "MF", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(5, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(5, 2)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/slope.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(5, 3)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/elevation.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(5, 4)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(5, 5)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(6, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "PL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(6, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "6", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(6, 2)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/slope.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(6, 3)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/elevation.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(6, 4)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(6, 5)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(7, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "SL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(7, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "7", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(7, 2)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(7, 3)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(7, 4)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(7, 5)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(8, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "WB", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(8, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "8", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(8, 2)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(8, 3)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(8, 4)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.item(8, 5)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/drivers/disttourban.img", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DriverSelectionT1), QtGui.QApplication.translate("LULCModel", "Driver Selection T1", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("LULCModel", "Select Drivers", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("LULCModel", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("LULCModel", "2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("LULCModel", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("LULCModel", "4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("LULCModel", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("LULCModel", "6", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.verticalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("LULCModel", "7", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.verticalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("LULCModel", "8", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.verticalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("LULCModel", "9", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("LULCModel", "Class", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("LULCModel", "slope", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("LULCModel", "elevation", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("LULCModel", "disttourban", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("LULCModel", "disttostream", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_5.isSortingEnabled()
        self.tableWidget_5.setSortingEnabled(False)
        item = self.tableWidget_5.item(0, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "BU", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.item(1, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "DBF", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.item(2, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "CL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.item(3, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "FL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.item(4, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "GL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.item(5, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "MF", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.item(6, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "PL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.item(7, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "SL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_5.item(8, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "WB", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_5.setSortingEnabled(__sortingEnabled)
        self.groupBox_5.setTitle(QtGui.QApplication.translate("LULCModel", "Migration Order", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("LULCModel", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("LULCModel", "2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("LULCModel", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("LULCModel", "4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("LULCModel", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("LULCModel", "6", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.verticalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("LULCModel", "7", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.verticalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("LULCModel", "8", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.verticalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("LULCModel", "9", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("LULCModel", "Class", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("LULCModel", "BU", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("LULCModel", "DBF", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("LULCModel", "CL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("LULCModel", "FL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("LULCModel", "GL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("LULCModel", "MF", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("LULCModel", "PL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.horizontalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("LULCModel", "SL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.horizontalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("LULCModel", "WB", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_6.isSortingEnabled()
        self.tableWidget_6.setSortingEnabled(False)
        item = self.tableWidget_6.item(0, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "BU", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.item(1, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "DBF", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.item(2, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "CL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.item(3, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "FL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.item(4, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "GL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.item(5, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "MF", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.item(6, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "PL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.item(7, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "SL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_6.item(8, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "WB", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_6.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CreateSutiabilityMap), QtGui.QApplication.translate("LULCModel", "Create Suitability Map", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("LULCModel", "Policies", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("LULCModel", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("LULCModel", "2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("LULCModel", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("LULCModel", "4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("LULCModel", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("LULCModel", "6", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("LULCModel", "Class", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("LULCModel", "Demand", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("LULCModel", "Restriction", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("LULCModel", "Spatial Context", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        item = self.tableWidget_4.item(0, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "BU", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.item(0, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "2316", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.item(0, 3)
        item.setText(QtGui.QApplication.translate("LULCModel", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.item(1, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "DBF", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.item(1, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "35245", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.item(2, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "CL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.item(2, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "11306", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.item(3, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "FL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.item(3, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "1762", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.item(4, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "GL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.item(4, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.item(5, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "MF", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_4.item(5, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "71", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        self.pushButton_8.setText(QtGui.QApplication.translate("LULCModel", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DemandAllocation), QtGui.QApplication.translate("LULCModel", "Demand Allocation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("LULCModel", "number Of File", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setText(QtGui.QApplication.translate("LULCModel", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("LULCModel", "Ouput Grid", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget1.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("LULCModel", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget1.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("LULCModel", "2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget1.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("LULCModel", "File Location", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget1.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("LULCModel", "Select", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget1.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("LULCModel", "Grid Size", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget1.isSortingEnabled()
        self.tableWidget1.setSortingEnabled(False)
        item = self.tableWidget1.item(0, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/ouput1.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget1.item(0, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget1.item(0, 2)
        item.setText(QtGui.QApplication.translate("LULCModel", "1000", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget1.item(1, 0)
        item.setText(QtGui.QApplication.translate("LULCModel", "/home/akjha/output2.img", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget1.item(1, 1)
        item.setText(QtGui.QApplication.translate("LULCModel", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget1.item(1, 2)
        item.setText(QtGui.QApplication.translate("LULCModel", "250", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget1.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(QtGui.QApplication.translate("LULCModel", "Compose Raster", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ComposeRaster), QtGui.QApplication.translate("LULCModel", "Compose Raster", None, QtGui.QApplication.UnicodeUTF8))

